name=liteFilters
version=1.0.0
author=stpntrsvv
maintainer=stpntrsvv
sentence=A lightweight signal filtering library for embedded systems.
paragraph=Includes EMA, Kalman, Median, and Moving Average filters with template support.
category=Signal Processing
lpurl=https://github.com/stpntrsvv/liteFilters
includes=liteFilters.h